### ISSUE TITLE
What is the DHT library that is used in this project?

### ISSUE THREAD

**Issue by hemangjoshi37a** [techiesms/ESP-RainMaker-Demo-Code#1]
Becuase there are so many DHT libraries so I dont know which one to use.
Please provide any link if possible.
[hjlabs.in](https://hjlabs.in)

**Comment by arunsuthar98** [comment]
use this lib.- https://github.com/adafruit/DHT-sensor-library

**Comment by hemangjoshi37a** [comment]
@arunsuthar98 @techiesms 
Thank you for the support. 👍👍👍👍
[hjlabs.in](https://hjlabs.in)
