### ISSUE TITLE
E(9141) and E(9142)

### ISSUE THREAD

**Issue by hwbmi** [techiesms/ESP-RainMaker-Demo-Code#2]
Hi,

Thanks for the good video. I followed your procedure on an ESP32 DevKit V4 module. But from the Arduino IDE Serial Monitor, it always shows errors like below,
```
E (9141) esp_rmaker_core: Node connected to Wi-Fi without Assisted claiming. Cannot proceed to MQTT connection.
E (9142) esp_rmaker_core: Please update your phone apps and repeat Wi-Fi provisioning with BLE transport.
```
Any idea?

--paul

**Comment by arunsuthar98** [comment]
first, check your esp rainmaker app is Updated 

after, if you have any PROV_ connection please remove it and try it again 

try to first sample code if it gives error then, there is a problem in your WIFi

and esp also working on there esp rainmaker cloud so sometimes it's giving an error but if you try again it will be solve

**Comment by hwbmi** [comment]
> first, check your esp rainmaker app is Updated
> 
> after, if you have any PROV_ connection please remove it and try it again
> 
> try to first sample code if it gives error then, there is a problem in your WIFi
> 
> and esp also working on there esp rainmaker cloud so sometimes it's giving an error but if you try again it will be solve

Hi arunsuthar98, thank you for the kind suggestions. 
1. Update the esp rainmaker app to latest - I downloaded and installed today, it's v2.7.0(6f004b8)
2. I have only only PROV_connection.
3.  I also tried the official example, RMakerSwitch, with the same errors.  
4. The errors happened right after reset, I didn't have a chance to use the app to provision it to my WiFi. 

Thank you again for answering.

**Comment by hwbmi** [comment]
Thanks to the inspiration from arunsuthar98. The issue is the residue of the WiFi settings from the previous sketch. The upload process doesn't erase that portion. By the instruction from offical doc,
`Press and hold the BOOT button for more than 3 seconds to reset the Wi-Fi setting.`

The wifi settings are reset and everything is working well.
